 
#cloud-config

hostname: rancher

rancher:
  network:
    interfaces:
      eth0:
        address: 192.168.1.62/24
        gateway: 192.168.1.1
        dhcp: false
    dns:
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
